-- MySQL Script generated by MySQL Workbench
-- Thu Feb 15 22:16:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wordbitweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wordbitweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wordbitweb` DEFAULT CHARACTER SET utf8 ;
USE `wordbitweb` ;

-- -----------------------------------------------------
-- Table `wordbitweb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordbitweb`.`groups` (
  `idgroups` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT now(),
  `modified` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`idgroups`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordbitweb`.`words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordbitweb`.`words` (
  `idwords` INT NOT NULL AUTO_INCREMENT,
  `english` VARCHAR(150) NOT NULL,
  `pronunciation` VARCHAR(150) NOT NULL,
  `sentence` VARCHAR(300) NULL,
  `spanish` VARCHAR(45) NOT NULL,
  `isrepeat` INT NOT NULL DEFAULT 0,
  `used` DATETIME NOT NULL DEFAULT now(),
  `group_id` INT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT now(),
  `modified` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`idwords`),
  INDEX `fk_words_groups_idx` (`group_id` ASC),
  CONSTRAINT `fk_words_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `wordbitweb`.`groups` (`idgroups`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
